export const FETCH_WALLET_REQUEST = "FETCH_WALLET_REQUEST";
export const FETCH_WALLET_SUCCESS = "FETCH_WALLET_SUCCESS";
export const FETCH_WALLET_FAILURE = "FETCH_WALLET_FAILURE";
export const FETCH_TRANSFER_REQUEST = "FETCH_TRANSFER_REQUEST";
export const FETCH_TRANSFER_SUCCESS = "FETCH_TRANSFER_SUCCESS";
export const FETCH_TRANSFER_FAILURE = "FETCH_TRANSFER_FAILURE";
